version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: zoo
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # So you don't have to use root, but you can if you like
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
## Names our volume
#volumes:
#  my-db: